name: Allure Reports test

on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Dependencies
        run: npm ci
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install Allure
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install allure
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        continue-on-error: true
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: allure-report
          path: allure-report
